language: android
android:
  components:
    - build-tools-27.0.3
    - android-27
  licenses:
    - 'android-sdk-license-.+'
  before_install:
    - yes | sdkmanager "platforms;android-27"
    - chmod +x gradlew
    - git submodule update --init --recursive
  install:
  - ./gradlew