language: android
before_install:
  - yes | sdkmanager "platforms;android-27"
  - chmod +x gradlew
env:
  global:
   - ADB_INSTALL_TIMEOUT=10 # minutes (2 minutes by default)
android:
  components:
    - build-tools-27.0.3
    - android-27
    - android-21
    - sys-img-armeabi-v7a-android-21
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
addons:
  sonarcloud:
    organization: lonesocket-github
    branches:
    - master
    - develop
    token:
      secure: R8NioWokIVMdnqEjADKrcripf8CwYp/egMJNARv1tj0AKQrvussbfS3Ljt/UsSp/sTF6ftUTP07PIyQMOfp2OQksmmRyBiHOQwypFWMI0pf1C5iEVMICpfH7j/miXTCI0qyR0BLEuVXgJ1XsOiwZONy5ACKym2nr20tHncSRvmGPZOM0pGcKsuQ8mWs2qvzn+ykOfFWxU0BlqnamAFbUvLMQk9LEYb+qhr+UFEB/gfaDAE0V+1vvt+XVjP+YXZWkGuosReO4AHmr3fczWuKRXYDduQsDylMTYeLaKkY99ZfOMNa+U8smh6ZFLoG4Zs5UJ2pPfc7IoxE/sBhnHmJFqbN4I7mypgET3O7bZIDmsE41PoODh6vhS2gEaZqHlHYfrKA2U0DaL03GlepAN/FAchVaXZ/s3p+wvsQ+S2czMnLZ2eygARVV2hHfvPwpfSGbTn96E7ecJFdP2qkvcOH0Du7v0UW3MdDK+UwJhrnt/a9geiotPOLjgZzXicIyK0EHwbRjz5Uhd8DXWZ1CrH8dNLBgu2m4oWpldmxb2mo/4l4M7eKW0DeSnrmTUtMIn4cEiGlRFNat3DbhTAqAGSkyfbUd86RX/cyrPPZN5fW6YFZjgvkZVf+o5cac3LaYgsKJcudD3gO15BxiY3QT1OLxiIjmA/Uu6P4q69ip7Tuakhw=
script:
- "./gradlew sonarqube"
